SELECT 'Hello there'
UNION
SELECT convert(VARCHAR(10),'Sam')
--

SELECT CONVERT(TINYINT,5) AS Values_
UNION
SELECT CONVERT(BIGINT,593904) AS Numbers_

--Union All allows duplication, UNION does not:

SELECT CONVERT(VARCHAR(20),'Hi,My name is Bob') AS Some_string
UNION
SELECT CONVERT(VARCHAR(10),'Hi')
UNION
SELECT CONVERT(VARCHAR(10),'Hello')
UNION ALL
SELECT CONVERT(VARCHAR(10),'Hi')
