--Globally Unique Identifiers:
DECLARE @val AS UNIQUEIDENTIFIER
SET @val = NEWID()
SELECT @val AS NewID

--
DECLARE @val AS UNIQUEIDENTIFIER
SET @val = NEWSEQUENTIALID()
SELECT @val AS NewID

---Sequences:
CREATE SEQUENCE myseq AS BIGINT
START WITH 1
MINVALUE 1
MAXVALUE 9999999
CYCLE
